---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: demo-autoscaler
  namespace: production
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demo-autoscaler
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale"]
  verbs: ["get", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demo-autoscaler
subjects:
- kind: ServiceAccount
  name: demo-autoscaler
  namespace: production
roleRef:
  kind: ClusterRole
  name: demo-autoscaler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: particles-v1.0.0
  namespace: production
  labels:
    app: particles
    version: 1.0.0
spec:
  selector:
    matchLabels:
      app: particles
      version: 1.0.0
  replicas: 4
  template:
    metadata:
      labels:
        app: particles
        version: 1.0.0
    spec:
      containers:
      - name: particles
        image: magneticio/particles:1.5.2
        imagePullPolicy: Always
        args:
          - "--color=#F0F5FA"
          - "--appVersion=v1.0.0"
          - "--showStats"
          - "--clusterCount=50"
          - "--particlesPerCluster=10"
          - "--minMem=300"
        env:
        - name: MEM_LIMIT
          valueFrom:
            resourceFieldRef:
              containerName: particles
              divisor: 1Mi
              resource: limits.memory
        ports:
        - containerPort: 5000
          name: http
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          failureThreshold: 1
        resources:
          limits:
            cpu: 1000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 64Mi
---
apiVersion: batch/v1
kind: Job
metadata:
  name: autoscaler-particles-v1.0.0
  namespace: production
spec:
  template:
    metadata:
      name: autoscaler-particles-v1.0.0
    spec:
      containers:
      - name: autoscaler
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: DEPLOYMENT_NAME
          value: particles-v1.0.0
        - name: DEPLOYMENT_LABELS
          value: app=particles,version=1.0.0
        - name: MIN_REPLICAS
          value: "2"
        - name: MAX_REPLICAS
          value: "4"
        - name: INITIAL_DELAY
          value: "60"
        image: magneticio/particles-autoscaler:0.1.24
      restartPolicy: OnFailure
      serviceAccountName: demo-autoscaler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-bench
  namespace: production
  annotations:
    vamp.io/release: "false"
spec:
  selector:
    matchLabels:
      app: apache-bench
  replicas: 1
  template:
    metadata:
      labels:
        app: apache-bench
    spec:
      containers:
        - name: apache-bench
          image: jordi/ab
          args:
          - "-c"
          - "9"
          - "-n"
          - "1000000"
          - "-H"
          - "Host: orb-test-app.vamp-dev.cloud"
          - "http://envoy.projectcontour/particles"