version: 2.1

orbs:
  gcp-gke: circleci/gcp-gke@1.1.0

parameters:
  delete:
    type: boolean
    default: false
  version:
    type: string
    default: ""
  kubernetes_cluster:
    type: string
    default: contentful-debug
  kubernetes_namespace:
    type: string
    default: production

jobs:
  update-deployment:
    docker:
      - image: cimg/base:stable
    steps:
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: << pipeline.parameters.kubernetes_cluster >>
          install-kubectl: true
          perform-login: true
      - checkout
      - run:
          name: Update Deployment
          command: |
            kubectl apply -f particles-v1.0.0.yaml -n << pipeline.parameters.kubernetes_namespace >>

  delete-deployment:
    docker:
      - image: cimg/base:stable
    steps:
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: << pipeline.parameters.kubernetes_cluster >>
          install-kubectl: true
          perform-login: true
      - checkout
      - run:
          name: Deleting Deployment
          command: |
            kubectl delete -f particles-v<< pipeline.parameters.version >>.yaml -n << pipeline.parameters.kubernetes_namespace >> --ignore-not-found

workflows:
  version: 2
  update:
    when:
      not: << pipeline.parameters.delete >>
    jobs:
      - update-deployment
  delete:
    when: << pipeline.parameters.delete >>
    jobs:
      - delete-deployment
